name: Build PDF from Markdown

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  convert-markdown-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install LaTeX
        run: |
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: Convert .md to PDF
        run: |
          pandoc README.md --pdf-engine=xelatex -o documentation.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: documentation.pdf
