name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-recommended

      - name: Install Pandoc
        run: |
          sudo apt-get install -y pandoc

      - name: Build documentation
        run: |
          pandoc README.md --pdf-engine=xelatex -o documentation.pdf

      - name: Upload generated PDF
        uses: actions/upload-artifact@v3
        with:
          name: documentation-pdf
          path: documentation.pdf
